# Generated by Django 3.1.1 on 2020-09-11 12:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_private',
            field=models.CharField(choices=[(0, 'no'), (1, 'yes')], default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=ckeditor.fields.RichTextField(max_length=5000, null=True),
        ),
    ]
