# Generated by Django 3.1.1 on 2020-09-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200911_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='heading',
        ),
        migrations.AddField(
            model_name='blog',
            name='sub_heading',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='time_to_read',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
